from flask.ext.wtf import Form
from wtforms import TextField, TextAreaField, SelectField, BooleanField, SubmitField, validators, ValidationError
from wtforms.validators import Required


class ContactForm(Form):
    name = TextField("Name", [validators.Required("Please enter your name.")])
    email = TextField("Email", [validators.Required("Please enter your email address."), validators.Email("Please enter your email address.")])
    subject = TextField("Subject", [validators.Required("Please enter a subject.")])
    message = TextAreaField("Message", [validators.Required("Please enter a message.")])
    submit = SubmitField("Send")


class ActiveEditForm(Form):
    
    #<!__ ROOT __>
    #xmlns = TextField('xmlns')
    #Timestamp = TextField('Timestamp')
    #Ack = TextField('Ack')
    #Version = TextField('Version')
    #Build = TextField('Build')

    #<!__ ITEM __>
    #AppData = TextField("AppData")


    #ItemId = TextField("ItemID")
    #Quantity = TextField("Quantity")
    #Email = TextField("Email")
    #Title = TextField('Title')
    #CONSTANTS for SELECT FIELDS
    LISTS = {}
    LISTS["Currency"] = {'NONE!': 'NONE!', 'AFA': 'AFA', 'ALL': 'ALL', 'DZD': 'DZD', 'ADP': 'ADP', 'AOA': 'AOA', 'ARS': 'ARS', 'AMD': 'AMD', 'AWG': 'AWG', 'AZM': 'AZM', 'BSD': 'BSD', 'BHD': 'BHD', 'BDT': 'BDT', 'BBD': 'BBD', 'BYR': 'BYR', 'BZD': 'BZD', 'BMD': 'BMD', 'BTN': 'BTN', 'INR': 'INR', 'BOV': 'BOV', 'BOB': 'BOB', 'BAM': 'BAM', 'BWP': 'BWP', 'BRL': 'BRL', 'BND': 'BND', 'BIF': 'BIF', 'KHR': 'KHR', 'CAD': 'CAD', 'CVE': 'CVE', 'KYD': 'KYD', 'XAF': 'XAF', 'CLF': 'CLF', 'CLP': 'CLP', 'CNY': 'CNY', 'COP': 'COP', 'KMF': 'KMF', 'CDF': 'CDF', 'CRC': 'CRC', 'HRK': 'HRK', 'CUP': 'CUP', 'CZK': 'CZK', 'DKK': 'DKK', 'DJF': 'DJF', 'DOP': 'DOP', 'TPE': 'TPE', 'EGP': 'EGP', 'ERN': 'ERN', 'EEK': 'EEK', 'ETB': 'ETB', 'FKP': 'FKP', 'FJD': 'FJD', 'GMD': 'GMD', 'GEL': 'GEL', 'GHC': 'GHC', 'GIP': 'GIP', 'GTQ': 'GTQ', 'GNF': 'GNF', 'GYD': 'GYD', 'HTG': 'HTG', 'HNL': 'HNL', 'HKD': 'HKD', 'HUF': 'HUF', 'ISK': 'ISK', 'IDR': 'IDR', 'IRR': 'IRR', 'IQD': 'IQD', 'ILS': 'ILS', 'JMD': 'JMD', 'JPY': 'JPY', 'JOD': 'JOD', 'KZT': 'KZT', 'KES': 'KES', 'AUD': 'AUD', 'KPW': 'KPW', 'KRW': 'KRW', 'KWD': 'KWD', 'KGS': 'KGS', 'LAK': 'LAK', 'LVL': 'LVL', 'LBP': 'LBP', 'LSL': 'LSL', 'LRD': 'LRD', 'LYD': 'LYD', 'CHF': 'CHF', 'LTL': 'LTL', 'MOP': 'MOP', 'MKD': 'MKD', 'MWK': 'MWK', 'MYR': 'MYR', 'MVR': 'MVR', 'EUR': 'EUR', 'MRO': 'MRO', 'MUR': 'MUR', 'MXN': 'MXN', 'MXV': 'MXV', 'MDL': 'MDL', 'MNT': 'MNT', 'XCD': 'XCD', 'MMK': 'MMK', 'ZAR': 'ZAR', 'NAD': 'NAD', 'NPR': 'NPR', 'ANG': 'ANG', 'XPF': 'XPF', 'NZD': 'NZD', 'NIO': 'NIO', 'NGN': 'NGN', 'NOK': 'NOK', 'OMR': 'OMR', 'PKR': 'PKR', 'PAB': 'PAB', 'PGK': 'PGK', 'PYG': 'PYG', 'PEN': 'PEN', 'PHP': 'PHP', 'PLN': 'PLN', 'USD': 'USD', 'QAR': 'QAR', 'RUB': 'RUB', 'RWF': 'RWF', 'SHP': 'SHP', 'WST': 'WST', 'STD': 'STD', 'SAR': 'SAR', 'SCR': 'SCR', 'SLL': 'SLL', 'SGD': 'SGD', 'SBD': 'SBD', 'SOS': 'SOS', 'LKR': 'LKR', 'SZL': 'SZL', 'SEK': 'SEK', 'SYP': 'SYP', 'TWD': 'TWD', 'TJS': 'TJS', 'TZS': 'TZS', 'THB': 'THB', 'XOF': 'XOF', 'TOP': 'TOP', 'TTD': 'TTD', 'TND': 'TND', 'UGX': 'UGX', 'UAH': 'UAH', 'AED': 'AED', 'GBP': 'GBP', 'USS': 'USS', 'USN': 'USN', 'UYU': 'UYU', 'UZS': 'UZS', 'VUV': 'VUV', 'VND': 'VND', 'MAD': 'MAD', 'YER': 'YER', 'YUM': 'YUM'}
    LISTS["CurrencyID"] = {'NONE!': 'NONE!', 'INR': 'INR', 'CAD': 'CAD', 'CNY': 'CNY', 'HKD': 'HKD', 'AUD': 'AUD', 'CHF': 'CHF', 'MYR': 'MYR', 'EUR': 'EUR', 'PHP': 'PHP', 'PLN': 'PLN', 'USD': 'USD', 'SGD': 'SGD', 'SEK': 'SEK', 'TWD': 'TWD', 'GBP': 'GBP'}
    LISTS["BuyerProt"] = {'UnKnown': 'UnKnown', 'ItemIneligible': 'ItemIneligible', 'ItemEligible': 'ItemEligible', 'ItemMarkedIneligible': 'ItemMarkedIneligible', 'ItemMarkedEligible': 'ItemMarkedEligible', 'NoCoverage': 'NoCoverage', 'CustomCode': 'CustomCode'}
    LISTS["Country"] = {'NONE!': 'NONE!', 'AF': 'Afghanistan', 'AL': 'Albania', 'DZ': 'Algeria', 'AS': 'American Samoa', 'AD': 'Andorra', 'AO': 'Angola', 'AI': 'Anguilla', 'AQ': 'Antarctica', 'AG': 'Antigua and Barbuda', 'AR': 'Argentina', 'AM': 'Armenia', 'AW': 'Aruba', 'AU': 'Australia', 'AT': 'Austria', 'AZ': 'Azerbaijan', 'BS': 'Bahamas', 'BH': 'Bahrain', 'BD': 'Bangladesh', 'BB': 'Barbados', 'BY': 'Belarus', 'BE': 'Belgium', 'BZ': 'Belize', 'BJ': 'Benin', 'BM': 'Bermuda', 'BT': 'Bhutan', 'BO': 'Bolivia', 'BA': 'Bosnia and Herzegovina', 'BW': 'Botswana', 'BV': 'Bouvet Island', 'BR': 'Brazil', 'IO': 'British Indian Ocean Territory', 'BN': 'Brunei Darussalam', 'BG': 'Bulgaria', 'BF': 'Burkina Faso', 'BI': 'Burundi', 'KH': 'Cambodia', 'CM': 'Cameroon', 'CA': 'Canada', 'CV': 'Cape Verde', 'KY': 'Cayman Islands', 'CF': 'Central African Republic', 'TD': 'Chad', 'CL': 'Chile', 'CN': 'China', 'CX': 'Christmas Island', 'CC': 'Cocos (Keeling) Islands', 'CO': 'Colombia', 'KM': 'Comoros', 'CG': 'Congo', 'CD': 'Congo, The Democratic Republic of the', 'CK': 'Cook Islands', 'CR': 'Costa Rica', 'CI': 'Cote d''Ivoire', 'HR': 'Croatia', 'CU': 'Cuba', 'CY': 'Cyprus', 'CZ': 'Czech Republic', 'DK': 'Denmark', 'DJ': 'Djibouti', 'DM': 'Dominica', 'DO': 'Dominican Republic', 'TP': 'No longer in use', 'EC': 'Ecuador', 'EG': 'Egypt', 'SV': 'El Salvador', 'GQ': 'Equatorial Guinea', 'ER': 'Eritrea', 'EE': 'Estonia', 'ET': 'Ethiopia', 'FK': 'Falkland Islands (Malvinas)', 'FO': 'Faroe Islands', 'FJ': 'Fiji', 'FI': 'Finland', 'FR': 'France', 'GF': 'French Guiana', 'PF': 'French Polynesia Includes Tahiti', 'TF': 'French Southern Territories', 'GA': 'Gabon', 'GM': 'Gambia', 'GE': 'Georgia', 'DE': 'Germany', 'GH': 'Ghana', 'GI': 'Gibraltar', 'GR': 'Greece', 'GL': 'Greenland', 'GD': 'Grenada', 'GP': 'Guadeloupe', 'GU': 'Guam', 'GT': 'Guatemala', 'GN': 'Guinea', 'GW': 'Guinea-Bissau', 'GY': 'Guyana', 'HT': 'Haiti', 'HM': 'Heard Island and McDonald Islands', 'VA': 'Holy See (Vatican City state)', 'HN': 'Honduras', 'HK': 'Hong Kong', 'HU': 'Hungary', 'IS': 'Iceland', 'IN': 'India', 'ID': 'Indonesia', 'IR': 'Islamic Republic of Iran', 'IQ': 'Iraq', 'IE': 'Ireland', 'IL': 'Israel', 'IT': 'Italy', 'JM': 'Jamaica', 'JP': 'Japan', 'JO': 'Jordan', 'KZ': 'Kazakhstan', 'KE': 'Kenya', 'KI': 'Kiribati', 'KP': 'Democratic People''s Republic of Korea', 'KR': 'Republic of Korea', 'KW': 'Kuwait', 'KG': 'Kyrgyzstan', 'LA': 'Lao People''s Democratic Republic', 'LV': 'Latvia', 'LB': 'Lebanon', 'LS': 'Lesotho', 'LR': 'Liberia', 'LY': 'Libyan Arab Jamahiriya', 'LI': 'Liechtenstein', 'LT': 'Lithuania', 'LU': 'Luxembourg', 'MO': 'Macao', 'MK': 'The Former Yugoslav Republic of Macedonia', 'MG': 'Madagascar', 'MW': 'Malawi', 'MY': 'Malaysia', 'MV': 'Maldives', 'ML': 'Mali', 'MT': 'Malta', 'MH': 'Marshall Islands', 'MQ': 'Martinique', 'MR': 'Mauritania', 'MU': 'Mauritius', 'YT': 'Mayotte', 'MX': 'Mexico', 'FM': 'Federated States of Micronesia', 'MD': 'Republic of Moldova', 'MC': 'Monaco', 'MN': 'Mongolia', 'MS': 'Montserrat', 'MA': 'Morocco', 'MZ': 'Mozambique', 'MM': 'Myanmar', 'NA': 'Namibia', 'NR': 'Nauru', 'NP': 'Nepal', 'NL': 'Netherlands', 'AN': 'Netherlands Antilles', 'NC': 'New Caledonia', 'NZ': 'New Zealand', 'NI': 'Nicaragua', 'NE': 'Niger', 'NG': 'Nigeria', 'NU': 'Niue', 'NF': 'Norfolk Island', 'MP': 'Northern Mariana Islands', 'NO': 'Norway', 'OM': 'Oman', 'PK': 'Pakistan', 'PW': 'Palau', 'PS': 'Palestinian territory, Occupied', 'PA': 'Panama', 'PG': 'Papua New Guinea', 'PY': 'Paraguay', 'PE': 'Peru', 'PH': 'Philippines', 'PN': 'Pitcairn', 'PL': 'Poland', 'PT': 'Portugal', 'PR': 'Puerto Rico', 'QA': 'Qatar', 'RE': 'Reunion', 'RO': 'Romania', 'RU': 'Russian Federation', 'RW': 'Rwanda', 'SH': 'Saint Helena', 'KN': 'Saint Kitts and Nevis', 'LC': 'Saint Lucia', 'PM': 'Saint Pierre and Miquelon', 'VC': 'Saint Vincent and the Grenadines', 'WS': 'Samoa', 'SM': 'San Marino', 'ST': 'Sao Tome and Principe', 'SA': 'Saudi Arabia', 'SN': 'Senegal', 'SC': 'Seychelles', 'SL': 'Sierra Leone', 'SG': 'Singapore', 'SK': 'Slovakia', 'SI': 'Slovenia', 'SB': 'Solomon Islands', 'SO': 'Somalia', 'ZA': 'South Africa', 'GS': 'South Georgia and the South Sandwich Islands', 'ES': 'Spain', 'LK': 'Sri Lanka', 'SD': 'Sudan', 'SR': 'Suriname', 'SJ': 'Svalbard and Jan Mayen', 'SZ': 'Swaziland', 'SE': 'Sweden', 'CH': 'Switzerland', 'SY': 'Syrian Arab Republic', 'TW': 'Taiwan, Province of China', 'TJ': 'Tajikistan', 'TZ': 'Tanzania, United Republic of', 'TH': 'Thailand', 'TG': 'Togo', 'TK': 'Tokelau', 'TO': 'Tonga', 'TT': 'Trinidad and Tobago', 'TN': 'Tunisia', 'TR': 'Turkey', 'TM': 'Turkmenistan', 'TC': 'Turks and Caicos Islands', 'TV': 'Tuvalu', 'UG': 'Uganda', 'UA': 'Ukraine', 'AE': 'United Arab Emirates', 'GB': 'United Kingdom', 'US': 'United States', 'UY': 'Uruguay', 'UZ': 'Uzbekistan', 'VU': 'Vanuatu', 'VE': 'Venezuela', 'VN': 'Vietnam', 'VG': 'Virgin Islands, British', 'VI': 'Virgin Islands, US', 'WF': 'Wallis and Futuna', 'EH': 'Western Sahara', 'YE': 'Yemen', 'ZM': 'Zambia', 'ZW': 'Zimbabwe', 'JE': 'Jersey', 'GG': 'Guernsey', 'ZZ': 'Unknown country', 'RS': 'Serbia', 'ME': 'Montenegro'}
    LISTS["HitCounter"] = {'NoHitCounter': 'NoHitCounter', 'HonestyStyle': 'HonestyStyle', 'GreenLED': 'GreenLED', 'Hidden': 'Hidden', 'BasicStyle': 'BasicStyle', 'RetroStyle': 'RetroStyle', 'HiddenStyle': 'HiddenStyle'}
    #for key, value in LISTS["CurrencyID"].iteritems():
    #    print "{0} = {1}".format(key, value)

    xmlns = TextField('xmlns')
    Timestamp = TextField('Timestamp')
    Ack = TextField('Ack')
    Version = TextField('Version')
    Build = TextField('Build')

    AppData = TextField('AppData')
    AutoPay = BooleanField('AutoPay')
    BuyerProtection = TextField('BuyerProtection')
    BuyItNowPrice_currencyID = SelectField('BuyItNowPrice_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    BuyItNowPrice_text = TextField('BuyItNowPrice_text')
    Country = SelectField('Country', coerce=str, default='NONE!', choices=LISTS["Country"].items())
    Currency = TextField('Currency')
    GiftIcon = TextField('GiftIcon') #, default='0', choices=[('1', 'ON'), ('0', 'OFF')])
    HitCounter = SelectField('HitCounter', coerce=str, default='NoHitCounter', choices=LISTS["HitCounter"].items())
    ItemId = TextField('ItemId')

    ListingDetails_Adult = BooleanField('ListingDetails_Adult')
    ListingDetails_BindingAuction = BooleanField('ListingDetails_BindingAuction')
    ListingDetails_CheckoutEnabled = BooleanField('ListingDetails_CheckoutEnabled')
    LDConvertedBuyItNowPrice_currencyID = TextField('LDConvertedBuyItNowPrice_currencyID') # LISTS["CurrencyID"].items())
    LDConvertedBuyItNowPrice_text = TextField('LDConvertedBuyItNowPrice_text')
    LDConvertedStartPrice_currencyID = TextField('LDConvertedStartPrice_currencyID') # LISTS["CurrencyID"].items())
    LDConvertedStartPrice_text = TextField('LDConvertedStartPrice_text')
    LDConvertedReservePrice_currencyID = TextField('LDConvertedReservePrice_currencyID') # LISTS["CurrencyID"].items())
    LDConvertedReservePrice_text = TextField('LDConvertedReservePrice_text')
    ListingDetails_HasReservePrice = BooleanField('ListingDetails_HasReservePrice')
    ListingDetails_StartTime = TextField('ListingDetails_StartTime')
    ListingDetails_EndTime = TextField('ListingDetails_EndTime')
    ListingDetails_ViewItemURL = TextField('ListingDetails_ViewItemURL')
    ListingDetails_HasUnansweredQuestions = BooleanField('ListingDetails_HasUnansweredQuestions')
    ListingDetails_HasPublicMessages = BooleanField('ListingDetails_HasPublicMessages')
    ListingDetails_ViewItemURLForNaturalSearch = TextField('ListingDetails_ViewItemURLForNaturalSearch')
    ListingDuration = TextField('ListingDuration')
    ListingType = TextField('ListingType')
    Location = TextField('Location')
    PaymentMethods = TextField('PaymentMethods')
    PayPalEmailAddress = TextField('PayPalEmailAddress')
    PrimaryCategory_CategoryID = TextField('PrimaryCategory_CategoryID')
    PrimaryCategory_CategoryName = TextField('PrimaryCategory_CategoryName')
    PrivateListing = BooleanField('PrivateListing')
    Quantity = TextField('Quantity')
    ReservePrice_currencyID = SelectField('ReservePrice_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    ReservePrice_text = TextField('ReservePrice_text')
    ReviseStatus_ItemRevised = BooleanField('ReviseStatus_ItemRevised')
    Seller_AboutMePage = BooleanField('Seller_AboutMePage')
    Seller_Email = TextField('Seller_Email')
    Seller_FeedbackScore = TextField('Seller_FeedbackScore')
    Seller_PositiveFeedbackPercent = TextField('Seller_PositiveFeedbackPercent')
    Seller_FeedbackPrivate = BooleanField('Seller_FeedbackPrivate')
    Seller_FeedbackRatingStar = TextField('Seller_FeedbackRatingStar')
    Seller_IDVerified = BooleanField('Seller_IDVerified')
    Seller_eBayGoodStanding = BooleanField('Seller_eBayGoodStanding')
    Seller_NewUser = BooleanField('Seller_NewUser')
    Seller_RegistrationDate = TextField('Seller_RegistrationDate')
    Seller_Site = TextField('Seller_Site')
    Seller_Status = TextField('Seller_Status')
    Seller_UserID = TextField('Seller_UserID')
    Seller_UserIDChanged = BooleanField('Seller_UserIDChanged')
    Seller_UserIDLastChanged = TextField('Seller_UserIDLastChanged')
    Seller_VATStatus = TextField('Seller_VATStatus')
    SSellerInfo_AllowPaymentEdit = BooleanField('SSellerInfo_AllowPaymentEdit')
    SSellerInfo_CheckoutEnabled = BooleanField('SSellerInfo_CheckoutEnabled')
    SSellerInfo_CIPBankAccountStored = BooleanField('SSellerInfo_CIPBankAccountStored')
    SSellerInfo_GoodStanding = BooleanField('SSellerInfo_GoodStanding')
    SSellerInfo_LiveAuctionAuthorized = BooleanField('SSellerInfo_LiveAuctionAuthorized')
    SSellerInfo_MerchandizingPref = TextField('SSellerInfo_MerchandizingPref')
    SSellerInfo_QualifiesForB2BVAT = BooleanField('SSellerInfo_QualifiesForB2BVAT')
    SSellerInfo_SellerLevel = TextField('SSellerInfo_SellerLevel')
    SSellerInfo_StoreOwner = BooleanField('SSellerInfo_StoreOwner')
    SSellerInfo_StoreURL = TextField('SSellerInfo_StoreURL')
    SSellerInfo_SafePaymentExempt = BooleanField('SSellerInfo_SafePaymentExempt')
    Seller_MotorsDealer = BooleanField('Seller_MotorsDealer')
    SellingStatus_BidCount = TextField('SellingStatus_BidCount')
    BidIncrement_currencyID = SelectField('BidIncrement_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    BidIncrement_text = TextField('BidIncrement_text')
    ConvertedCurrentPrice_currencyID = TextField('ConvertedCurrentPrice_currencyID') # LISTS["CurrencyID"].items())
    ConvertedCurrentPrice_text = TextField('ConvertedCurrentPrice_text')
    CurrentPrice_currencyID = TextField('CurrentPrice_currencyID') # LISTS["CurrencyID"].items())
    CurrentPrice_text = TextField('CurrentPrice_text')
    SellingStatus_LeadCount = TextField('SellingStatus_LeadCount')
    MinimumToBid_currencyID = SelectField('MinimumToBid_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    MinimumToBid_text = TextField('MinimumToBid_text')
    SellingStatus_QuantitySold = TextField('SellingStatus_QuantitySold')
    SellingStatus_ReserveMet = BooleanField('SellingStatus_ReserveMet')
    SellingStatus_SecondChanceEligible = BooleanField('SellingStatus_SecondChanceEligible')
    SellingStatus_ListingStatus = TextField('SellingStatus_ListingStatus')
    SellingStatus_QuantitySoldByPickupInStore = TextField('SellingStatus_QuantitySoldByPickupInStore')
    ShippingDetails_ApplyShippingDiscount = BooleanField('ShippingDetails_ApplyShippingDiscount')
    SDInsuranceOption = TextField('SDInsuranceOption')
    CalculatedShippingRate_OriginatingPostalCode = TextField('CalculatedShippingRate_OriginatingPostalCode')

    CSRPackageDepth_measurementSystem = TextField('CSRPackageDepth_measurementSystem')
    CSRPackageDepth_unit = TextField('CSRPackageDepth_unit')
    CSRPackageDepth_text = TextField('CSRPackageDepth_text')

    CSRPackageLength_measurementSystem = TextField('CSRPackageLength_measurementSystem')
    CSRPackageLength_unit = TextField('CSRPackageLength_unit')
    CSRPackageLength_text = TextField('CSRPackageLength_text')

    CSRPackageWidth_measurementSystem = TextField('CSRPackageWidth_measurementSystem')
    CSRPackageWidth_unit = TextField('CSRPackageWidth_unit')
    CSRPackageWidth_text = TextField('CSRPackageWidth_text')

    CSRPackageHandlingCosts_currencyID = SelectField('CSRPackageHandlingCosts_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    CSRPackageHandlingCosts_text = TextField('CSRPackageHandlingCosts_text')

    CalculatedShippingRate_ShippingIrregular = BooleanField('CalculatedShippingRate_ShippingIrregular')
    CalculatedShippingRate_ShippingPackage = TextField('CalculatedShippingRate_ShippingPackage')
    CSRWeightMajor_measurementSystem = TextField('CSRWeightMajor_measurementSystem')
    CSRWeightMajor_unit = TextField('CSRWeightMajor_unit')
    CSRWeightMajor_text = TextField('CSRWeightMajor_text')
    CSRWeightMinor_measurementSystem = TextField('CSRWeightMinor_measurementSystem')
    CSRWeightMinor_unit = TextField('CSRWeightMinor_unit')
    CSRWeightMinor_text = TextField('CSRWeightMinor_text')

    InsuranceFee_currencyID = SelectField('InsuranceFee_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    InsuranceFee_text = TextField('InsuranceFee_text')

    SalesTax_SalesTaxPercent = TextField('SalesTax_SalesTaxPercent')
    SalesTax_ShippingIncludedInTax = BooleanField('SalesTax_ShippingIncludedInTax')
    ShippingService = TextField('ShippingService')
    SSOShippingServiceCost_currencyID = SelectField('SSOShippingServiceCost_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    SSOShippingServiceCost_text = TextField('SSOShippingServiceCost_text')
    ShippingServiceOptions_ShippingService = TextField('ShippingServiceOptions_ShippingService')
    ShippingServiceOptions_ShippingServicePriority = TextField('ShippingServiceOptions_ShippingServicePriority')
    ShippingServiceOptions_ExpeditedService = BooleanField('ShippingServiceOptions_ExpeditedService')
    ShippingServiceOptions_ShippingTimeMin = TextField('ShippingServiceOptions_ShippingTimeMin')
    ShippingServiceOptions_ShippingTimeMax = TextField('ShippingServiceOptions_ShippingTimeMax')
    ShippingServiceOptions_FreeShipping = TextField('ShippingServiceOptions_FreeShipping')
    IntShippingServiceOption_ShippingService = TextField('IntShippingServiceOption_ShippingService')
    IntShippingServiceOption_ShippingServicePriority  = TextField('IntShippingServiceOption_ShippingServicePriority')
    IntShippingServiceOption_ShipToLocation = TextField('IntShippingServiceOption_ShipToLocation')
    ShippingType = TextField('ShippingType')
    ThirdPartyCheckout = BooleanField('ThirdPartyCheckout')
    InsuranceDetails_InsuranceOption = TextField('InsuranceDetails_InsuranceOption')
    InternationalInsuranceDetails_InsuranceOption = TextField('InternationalInsuranceDetails_InsuranceOption')
    ShippingDetails_ShippingDiscountProfileID = TextField('ShippingDetails_ShippingDiscountProfileID')
    ShippingDetails_InternationalShippingDiscountProfile  = TextField('ShippingDetails_InternationalShippingDiscountProfile')
    ShippingDetails_SellerExcludeShipToLocationsPreferen  = TextField('ShippingDetails_SellerExcludeShipToLocationsPreferen')
    ShipToLocations = TextField('ShipToLocations')
    Site = TextField('Site')
    StartPrice_currencyID = SelectField('StartPrice_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    StartPrice_text = TextField('StartPrice_text')
    Storefront_StoreCategoryID = TextField('Storefront_StoreCategoryID')
    Storefront_StoreCategory2ID = TextField('Storefront_StoreCategory2ID')
    Storefront_StoreURL = TextField('Storefront_StoreURL')
    TimeLeft = TextField('TimeLeft')
    Title = TextField('Title')
    HitCount = TextField('HitCount')
    LocationDefaulted = BooleanField('LocationDefaulted')
    GetItFast = BooleanField('GetItFast')
    BuyerResponsibleForShipping = BooleanField('BuyerResponsibleForShipping')
    SKU = TextField('SKU')
    PostalCode = TextField('PostalCode')
    PictureDetails_GalleryType = TextField('PictureDetails_GalleryType')
    PictureDetails_GalleryURL = TextField('PictureDetails_GalleryURL')
    PictureDetails_PhotoDisplay = TextField('PictureDetails_PhotoDisplay')
    PictureDetails_PictureURL = TextAreaField("PictureDetails_PictureURL")
    DispatchTimeMax = TextField('DispatchTimeMax')
    ProxyItem = BooleanField('ProxyItem')
    BuyerGuaranteePrice_currencyID = SelectField('BuyerGuaranteePrice_currencyID', coerce=str, default='NONE!', choices=LISTS["CurrencyID"].items())
    BuyerGuaranteePrice_text = TextField('BuyerGuaranteePrice_text')
    BuyerRequirementDetails_MinimumFeedbackScore = TextField('BuyerRequirementDetails_MinimumFeedbackScore')
    BRDMaximumUnpaidItemStrikesInfo_Count = TextField('BRDMaximumUnpaidItemStrikesInfo_Count')
    BRDMaximumUnpaidItemStrikesInfo_Period = TextField('BRDMaximumUnpaidItemStrikesInfo_Period')
    IntangibleItem = BooleanField('IntangibleItem')
    ReturnPolicy_RefundOption = TextField('ReturnPolicy_RefundOption')
    ReturnPolicy_Refund = TextField('ReturnPolicy_Refund')
    ReturnPolicy_ReturnsWithinOption = TextField('ReturnPolicy_ReturnsWithinOption')
    ReturnPolicy_ReturnsWithin = TextField('ReturnPolicy_ReturnsWithin')
    ReturnPolicy_ReturnsAcceptedOption = TextField('ReturnPolicy_ReturnsAcceptedOption')
    ReturnPolicy_ReturnsAccepted = TextField('ReturnPolicy_ReturnsAccepted')
    ReturnPolicy_Description = TextField('ReturnPolicy_Description')
    ReturnPolicy_ShippingCostPaidByOption = TextField('ReturnPolicy_ShippingCostPaidByOption')
    ReturnPolicy_ShippingCostPaidBy = TextField('ReturnPolicy_ShippingCostPaidBy')
    ReturnPolicy_RestockingFeeValue = TextField('ReturnPolicy_RestockingFeeValue')
    ReturnPolicy_RestockingFeeValueOption = TextField('ReturnPolicy_RestockingFeeValueOption')
    ConditionDescription = TextField('ConditionDescription')
    PostCheckoutExperienceEnabled = BooleanField('PostCheckoutExperienceEnabled')
    SPShippingProfileID = TextField('SPShippingProfileID')
    SPShippingProfileName = TextField('SPShippingProfileName')
    SPReturnProfileID = TextField('SPReturnProfileID')
    SPReturnProfileName = TextField('SPReturnProfileName')
    SPPaymentProfileID = TextField('SPPaymentProfileID')
    SPPaymentProfileName = TextField('SPPaymentProfileName')
    ShippingPackageDetails_ShippingIrregular = BooleanField('ShippingPackageDetails_ShippingIrregular')
    ShippingPackageDetails_ShippingPackage = TextField('ShippingPackageDetails_ShippingPackage')

    SDPackageDepth_measurementSystem = TextField('SDPackageDepth_measurementSystem')
    SDPackageDepth_unit = TextField('SDPackageDepth_unit')
    SDPackageDepth_text = TextField('SDPackageDepth_text')

    SDPackageLength_measurementSystem = TextField('SDPackageLength_measurementSystem')
    SDPackageLength_unit = TextField('SDPackageLength_unit')
    SDPackageLength_text = TextField('SDPackageLength_text')

    SDPackageWidth_measurementSystem = TextField('SDPackageWidth_measurementSystem')
    SDPackageWidth_unit = TextField('SDPackageWidth_unit')
    SDPackageWidth_text = TextField('SDPackageWidth_text')


    SDWeightMajor_measurementSystem = TextField('SDWeightMajor_measurementSystem')
    SDWeightMajor_unit = TextField('SDWeightMajor_unit')
    SDWeightMajor_text = TextField('SDWeightMajor_text')
    SDWeightMinor_measurementSystem = TextField('SDWeightMinor_measurementSystem')
    SDWeightMinor_unit = TextField('SDWeightMinor_unit')
    SDWeightMinor_text = TextField('SDWeightMinor_text')
    RelistParentID = TextField('RelistParentID')
    HideFromSearch = BooleanField('HideFromSearch')


    submit = SubmitField("Update Item!")



class EbayStoreForm(Form):
    submit = SubmitField("Authorize Access to My eBay Data.")
    
class EtsyStoreForm(Form):
    submit = SubmitField("Authorize Access to My Etsy Data.")
